/*
 Highmaps JS v1.0.0-beta (2014-02-24)

 (c) 2011-2014 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(h){var j=h.Axis,x=h.Chart,o=h.Color,y=h.Legend,t=h.LegendSymbolMixin,u=h.Series,k=h.each,p=h.extend,z=h.extendClass,q=h.merge,r=h.pick,v=h.numberFormat,l=h.seriesTypes,w=h.wrap,m=function(){},s=h.ColorAxis=function(){this.isColorAxis=!0;this.init.apply(this,arguments)};p(s.prototype,j.prototype);p(s.prototype,{defaultColorAxisOptions:{lineWidth:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},color:"gray",width:0.01},labels:{overflow:"justify"},
minColor:"#EFEFFF",maxColor:"#003875"},init:function(b,a){var e=b.options.legend.layout!=="vertical",c;c=q(this.defaultColorAxisOptions,{side:e?2:1,reversed:!e},a,{isX:e,opposite:!e,showEmpty:!1,title:null,isColor:!0});j.prototype.init.call(this,b,c);a.dataClasses&&this.initDataClasses(a);this.isXAxis=!0;this.horiz=e;this.zoomEnabled=!1},tweenColors:function(b,a,e){for(var c=4,d,f=[];c--;)d=a.rgba[c]+(b.rgba[c]-a.rgba[c])*(1-e),f[c]=c===3?d:Math.round(d);return"rgba("+f.join(",")+")"},initDataClasses:function(b){var a=
this,e=this.chart,c,d=0,f=this.options;this.dataClasses=c=[];k(b.dataClasses,function(g,i){var h,g=q(g);c.push(g);if(!g.color)f.dataClassColor==="category"?(h=e.options.colors,g.color=h[d++],d===h.length&&(d=0)):g.color=a.tweenColors(o(f.minColor),o(f.maxColor),i/(b.dataClasses.length-1))})},setOptions:function(b){j.prototype.setOptions.call(this,b);this.options.crosshair=this.options.marker;this.stops=b.stops||[[0,this.options.minColor],[1,this.options.maxColor]];k(this.stops,function(a){a.color=
o(a[1])});this.coll="colorAxis"},setAxisSize:function(){var b=this.legendSymbol,a=this.chart;if(b)this.left=b.x,this.top=b.y,this.width=b.width,this.height=b.height,this.right=a.chartWidth-this.left-this.width,this.bottom=a.chartHeight-this.top-this.height,this.len=this.horiz?this.width:this.height,this.pos=this.horiz?this.left:this.top},toColor:function(b,a){var e,c=this.stops,d,f=this.dataClasses,g,i;if(f)for(i=f.length;i--;){if(g=f[i],d=g.from,c=g.to,(d===void 0||b>=d)&&(c===void 0||b<=c)){e=g.color;
if(a)a.dataClass=i;break}}else{this.isLog&&(b=this.val2lin(b));e=1-(this.max-b)/(this.max-this.min);for(i=c.length;i--;)if(e>c[i][0])break;d=c[i]||c[i+1];c=c[i+1]||d;e=1-(c[0]-e)/(c[0]-d[0]||1);e=this.tweenColors(d.color,c.color,e)}return e},getOffset:function(){var b=this.legendGroup;if(b&&(j.prototype.getOffset.call(this),!this.axisGroup.parentGroup))this.axisGroup.add(b),this.gridGroup.add(b),this.labelGroup.add(b),this.added=!0},setLegendColor:function(){var b,a=this.options;b=this.horiz?[0,0,
1,0]:[0,0,0,1];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:a.stops||[[0,a.minColor],[1,a.maxColor]]}},drawLegendSymbol:function(b,a){var e=b.padding,c=b.options,d=this.horiz,f=r(c.symbolWidth,d?200:12),g=r(c.symbolHeight,d?12:200),c=r(c.labelPadding,d?10:30);this.setLegendColor();a.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,f,g).attr({zIndex:1}).add(a.legendGroup);a.legendSymbol.getBBox();this.legendItemWidth=f+e+(d?0:c);this.legendItemHeight=g+e+(d?c:0)},setState:m,
visible:!0,setVisible:m,getSeriesExtremes:function(){var b;if(this.series.length)b=this.series[0],this.dataMin=b.valueMin,this.dataMax=b.valueMax},drawCrosshair:function(b,a){var e=!this.cross,c=a&&a.plotX,d=a&&a.plotY,f,g=this.pos,i=this.len;if(a)f=this.toPixels(a.value),f<g?f=g-2:f>g+i&&(f=g+i+2),a.plotX=f,a.plotY=this.len-f,j.prototype.drawCrosshair.call(this,b,a),a.plotX=c,a.plotY=d,!e&&this.cross&&this.cross.attr({fill:this.crosshair.color}).add(this.labelGroup)},getPlotLinePath:function(b,a,
e,c,d){return d?this.horiz?["M",d-4,this.top-6,"L",d+4,this.top-6,d,this.top,"Z"]:["M",this.left,d,"L",this.left-6,d+6,this.left-6,d-6,"Z"]:j.prototype.getPlotLinePath.call(this,b,a,e,c)},update:function(b,a){k(this.series,function(a){a.isDirtyData=!0});j.prototype.update.call(this,b,a);this.legendItem&&(this.setLegendColor(),this.chart.legend.colorizeItem(this,!0))},getDataClassLegendSymbols:function(){var b=this,a=this.chart,e=[],c=a.options.legend,d=c.valueDecimals,f=c.valueSuffix||"",g;k(this.dataClasses,
function(c,h){var j=!0,l=c.from,n=c.to;g="";l===void 0?g="< ":n===void 0&&(g="> ");l!==void 0&&(g+=v(l,d)+f);l!==void 0&&n!==void 0&&(g+=" - ");n!==void 0&&(g+=v(n,d)+f);e.push(p({chart:a,name:g,options:{},drawLegendSymbol:t.drawRectangle,visible:!0,setState:m,setVisible:function(){j=this.visible=!j;k(b.series,function(a){k(a.points,function(a){a.dataClass===h&&a.setVisible(j)})});a.legend.colorizeItem(this,j)}},c))});return e},name:""});w(x.prototype,"getAxes",function(b){var a=this.options.colorAxis;
b.call(this);this.colorAxis=[];a&&new s(this,a)});w(y.prototype,"getAllItems",function(b){var a=[],e=this.chart.colorAxis[0];e&&(e.options.dataClasses?a=a.concat(e.getDataClassLegendSymbols()):a.push(e),k(e.series,function(a){a.options.showInLegend=!1}));return a.concat(b.call(this))});l.heatmap=z(l.scatter,q({pointAttrToOptions:{stroke:"borderColor","stroke-width":"borderWidth",fill:"color",dashstyle:"dashStyle"},pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],optionalAxis:"colorAxis",
trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:m,parallelArrays:["x","y","value"],translateColors:function(){var b=this,a=this.options.nullColor,e=this.colorAxis;k(this.data,function(c){var d=c.value;if(d=d===null?a:e?e.toColor(d,c):c.color||b.color)c.color=d})}},{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,supportsDrilldown:!0,getExtremesFromAll:!0,init:function(){l.scatter.prototype.init.apply(this,arguments);this.pointRange=this.options.colsize||1},translate:function(){var b=
this.options,a=this.xAxis,e=this.yAxis;this.generatePoints();k(this.points,function(c){var d=(b.colsize||1)/2,f=(b.rowsize||1)/2,g=Math.round(a.len-a.translate(c.x-d,0,1,0,1)),d=Math.round(a.len-a.translate(c.x+d,0,1,0,1)),h=Math.round(e.translate(c.y-f,0,1,0,1)),f=Math.round(e.translate(c.y+f,0,1,0,1));c.plotY=1;c.shapeType="rect";c.shapeArgs={x:Math.min(g,d),y:Math.min(h,f),width:Math.abs(d-g),height:Math.abs(f-h)}});this.pointRange=b.colsize||1;this.translateColors()},drawPoints:l.column.prototype.drawPoints,
animate:m,getBox:m,drawLegendSymbol:t.drawRectangle,getExtremes:function(){u.prototype.getExtremes.call(this,this.valueData);this.valueMin=this.dataMin;this.valueMax=this.dataMax;u.prototype.getExtremes.call(this)}}))})(Highcharts);
